#  Futu Algo: Algorithmic High-Frequency Trading Framework
#  Copyright (c)  billpwchan - All Rights Reserved
#  Unauthorized copying of this file, via any medium is strictly prohibited
#  Proprietary and confidential
#  Written by Bill Chan <billpwchan@hotmail.com>, 2021

# the first step is always the same: import all necessary components:
import configparser
import smtplib
from socket import gaierror

from util import logger


class Email:
    def __init__(self):
        """
            Email Engine Constructor
        """
        self.config = configparser.ConfigParser()
        self.config.read("config.ini")

        self.port = self.config['Email'].get('port')
        self.smtp_server = self.config['Email'].get('smtp_server')
        self.login = self.config['Email'].get('login')  # paste your login generated by Mailtrap
        self.password = self.config['Email'].get('password')  # paste your password generated by Mailtrap

        self.default_logger = logger.get_logger("email")

    def write_email(self, receiver_name, message_content):
        # specify the sender’s and receiver’s email addresses
        sender = "from@example.com"
        receiver = receiver_name

        # type your message: use two newlines (\n) to separate the subject from the message body, and use 'f' to  automatically insert variables in the text
        message = f"""\
        Subject: Hi Mailtrap
        To: {receiver}
        From: {sender}
        {message_content}"""
        try:
            # send your message with credentials specified above
            with smtplib.SMTP(self.smtp_server, self.port) as server:
                server.login(self.login, self.password)
                server.sendmail(sender, receiver, message)

            print('Sent')
        except (gaierror, ConnectionRefusedError):
            print('Failed to connect to the server. Bad connection settings?')
        except smtplib.SMTPServerDisconnected:
            print('Failed to connect to the server. Wrong user/password?')
        except smtplib.SMTPException as e:
            print('SMTP error occurred: ' + str(e))
